import { FastifyInstance } from "fastify";
import { githubClient } from "../integrations/github/github-client";
import { gitlabClient } from "../integrations/gitlab/gitlab-client";
import { jiraClient } from "../integrations/jira/jira-client";
import { jitbitClient } from "../integrations/jitbit/jitbit-client";
import { ticketToTaskGenerator } from "../engineering/ticket-to-task";
import { env } from "../config/env";
import type { TicketSourceType } from "../integrations/source-resolver";

const AI_BRANCH_PREFIX = "ai/issue-";
const DEFAULT_WORK_LABEL = "ready-for-agent";

interface NormalizedWorkItem {
  id: string;
  type: string;
  title: string;
  number: number;
  url: string;
  owner: string;
  repo: string;
  labels: string[];
  suggestedBranch: string;
}

export async function autonomousLoopRoutes(fastify: FastifyInstance) {
  fastify.get("/work", async (request, _reply) => {
    const query = request.query as {
      repo?: string;
      owner?: string;
      label?: string;
      limit?: string;
      source?: string;
    };

    const source = (query.source || "auto") as TicketSourceType | "auto";
    const label = query.label || DEFAULT_WORK_LABEL;
    const limit = Math.min(parseInt(query.limit || "10", 10), 50);

    try {
      let items: NormalizedWorkItem[] = [];

      const resolvedSource = await resolveSource(source, query);

      switch (resolvedSource) {
        case "github":
          items = await fetchGitHubWork(label, limit, query);
          break;
        case "gitlab":
          items = await fetchGitLabWork(label, limit);
          break;
        case "jira":
          items = await fetchJiraWork(label, limit);
          break;
        case "jitbit":
          items = await fetchJitbitWork(label, limit);
          break;
      }

      return { success: true, items, total: items.length };
    } catch (err) {
      return { success: false, error: (err as Error).message };
    }
  });

  fastify.post("/pr", async (request, _reply) => {
    const body = request.body as {
      owner?: string;
      repo?: string;
      title: string;
      head: string;
      base?: string;
      body?: string;
      issueNumber?: number;
    };

    if (!body.title || !body.head) {
      return { success: false, error: "title and head (branch) are required" };
    }

    const owner = body.owner || env.GITHUB_DEFAULT_OWNER;
    const repo = body.repo || env.GITHUB_DEFAULT_REPO;

    if (!owner || !repo) {
      return {
        success: false,
        error: "owner and repo are required (or set GITHUB_DEFAULT_OWNER/REPO)",
      };
    }

    const prBody =
      body.body ??
      (body.issueNumber
        ? `Closes #${body.issueNumber}\n\n_Generated by AiRemoteCoder autonomous agent._`
        : "_Generated by AiRemoteCoder autonomous agent._");

    try {
      const pr = await githubClient.createPullRequest(
        {
          title: body.title,
          body: prBody,
          head: body.head,
          base: body.base || "main",
        },
        owner,
        repo,
      );

      return { success: true, prNumber: pr.number, url: pr.html_url };
    } catch (err) {
      return { success: false, error: (err as Error).message };
    }
  });

  fastify.post("/complete", async (request, _reply) => {
    const body = request.body as {
      owner?: string;
      repo?: string;
      issueNumber: number;
      prNumber: number;
      branchName: string;
      agentExitCode?: number;
    };

    if (!body.issueNumber || !body.prNumber) {
      return {
        success: false,
        error: "issueNumber and prNumber are required",
      };
    }

    const owner = body.owner || env.GITHUB_DEFAULT_OWNER;
    const repo = body.repo || env.GITHUB_DEFAULT_REPO;

    try {
      await githubClient.addIssueComment(
        body.issueNumber,
        `🤖 **AiRemoteCoder completed work**\n\n- Branch: \`${body.branchName}\`\n- PR: #${body.prNumber}\n- Exit code: ${body.agentExitCode ?? "unknown"}\n\nReview is in progress.`,
        owner,
        repo,
      );

      return { success: true, acknowledged: true };
    } catch (err) {
      return { success: false, error: (err as Error).message };
    }
  });

  // Create a GitLab merge request
  fastify.post("/mr", async (request, _reply) => {
    const body = request.body as {
      project?: string;
      title: string;
      sourceBranch: string;
      targetBranch?: string;
      description?: string;
      labels?: string;
      removeSourceBranch?: boolean;
    };

    if (!body.title || !body.sourceBranch) {
      return { success: false, error: "title and sourceBranch are required" };
    }

    const projectId = body.project || env.GITLAB_DEFAULT_PROJECT;
    if (!projectId) {
      return { success: false, error: "project is required (or set GITLAB_DEFAULT_PROJECT)" };
    }

    try {
      const mr = await gitlabClient.createMergeRequest(projectId, {
        title: body.title,
        sourceBranch: body.sourceBranch,
        targetBranch: body.targetBranch || "main",
        description: body.description ?? "_Generated by AiRemoteCoder autonomous agent._",
        labels: body.labels,
        removeSourceBranch: body.removeSourceBranch ?? true,
      });

      return {
        success: true,
        mrIid: mr.iid,
        url: mr.web_url,
      };
    } catch (err) {
      return { success: false, error: (err as Error).message };
    }
  });

  // Post completion comment on a Jira issue
  fastify.post("/complete/jira", async (request, _reply) => {
    const body = request.body as {
      issueKey: string;
      branchName: string;
      mrUrl?: string;
      mrIid?: number;
      agentExitCode?: number;
    };

    if (!body.issueKey) {
      return { success: false, error: "issueKey is required" };
    }

    try {
      const commentBody = `🤖 **AiRemoteCoder completed work**\n\n- Branch: \`${body.branchName}\`${body.mrUrl ? `\n- MR: ${body.mrUrl}` : body.mrIid ? `\n- MR: !${body.mrIid}` : ""}\n- Exit code: ${body.agentExitCode ?? "unknown"}\n\nReview is in progress.`;

      await jiraClient.addComment(body.issueKey, commentBody);

      return { success: true, acknowledged: true };
    } catch (err) {
      return { success: false, error: (err as Error).message };
    }
  });
}

function makeBranchName(issueNumber: number, title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40);
  return slug
    ? `${AI_BRANCH_PREFIX}${issueNumber}-${slug}`
    : `${AI_BRANCH_PREFIX}${issueNumber}`;
}

function resolveSource(
  source: TicketSourceType | "auto",
  query: { owner?: string; repo?: string },
): TicketSourceType {
  if (source !== "auto") return source;

  // Auto-detect: use whichever integration is configured
  if (query.owner || query.repo || env.GITHUB_DEFAULT_OWNER || env.GITHUB_DEFAULT_REPO) {
    return "github";
  }
  if (env.GITLAB_DEFAULT_PROJECT) return "gitlab";
  if (env.JIRA_BASE_URL) return "jira";
  if (env.JITBIT_ENABLED) return "jitbit";

  return "github";
}

async function fetchGitHubWork(
  label: string,
  limit: number,
  query: { owner?: string; repo?: string },
): Promise<NormalizedWorkItem[]> {
  const owner = query.owner || env.GITHUB_DEFAULT_OWNER;
  const repo = query.repo || env.GITHUB_DEFAULT_REPO;

  if (!owner || !repo) {
    throw new Error("owner and repo are required for GitHub (or set GITHUB_DEFAULT_OWNER/REPO)");
  }

  const issues = await githubClient.listIssues("open", label, owner, repo);

  return issues
    .filter((issue: any) => {
      if (issue.pull_request) return false;
      const issueLabels: string[] = (issue.labels || []).map((l: any) =>
        typeof l === "string" ? l : l.name,
      );
      if (issueLabels.includes("missing-coding-prompt")) return false;
      return ticketToTaskGenerator.hasCodingPromptContent(issue.body || "");
    })
    .slice(0, limit)
    .map((issue: any) => ({
      id: String(issue.number),
      type: "github_issue" as const,
      title: issue.title,
      number: issue.number,
      url: issue.html_url,
      owner,
      repo,
      labels: (issue.labels || []).map((l: any) =>
        typeof l === "string" ? l : l.name,
      ),
      suggestedBranch: makeBranchName(issue.number, issue.title),
    }));
}

async function fetchGitLabWork(
  label: string,
  limit: number,
): Promise<NormalizedWorkItem[]> {
  if (!env.GITLAB_DEFAULT_PROJECT) {
    throw new Error("GITLAB_DEFAULT_PROJECT is required for GitLab source");
  }

  const issues = await gitlabClient.listIssues(
    env.GITLAB_DEFAULT_PROJECT,
    "opened",
    label,
  );

  return issues
    .filter((issue: any) => {
      const issueLabels: string[] = (issue.labels || []);
      if (issueLabels.includes("missing-coding-prompt")) return false;
      return ticketToTaskGenerator.hasCodingPromptContent(issue.description || "");
    })
    .slice(0, limit)
    .map((issue: any) => ({
      id: String(issue.iid),
      type: "gitlab_issue" as const,
      title: issue.title,
      number: issue.iid,
      url: issue.web_url,
      owner: String(issue.project_id),
      repo: env.GITLAB_DEFAULT_PROJECT!,
      labels: issue.labels || [],
      suggestedBranch: makeBranchName(issue.iid, issue.title),
    }));
}

async function fetchJiraWork(
  label: string,
  limit: number,
): Promise<NormalizedWorkItem[]> {
  if (!env.JIRA_BASE_URL) {
    throw new Error("JIRA_BASE_URL is required for Jira source");
  }

  const jql = `labels = "${label}" AND statusCategory in ("To Do", "In Progress") ORDER BY priority ASC`;
  const issues = await jiraClient.searchIssues(jql, limit);

  return issues
    .filter((issue: any) => {
      const issueLabels: string[] = issue.fields?.labels || [];
      if (issueLabels.includes("missing-coding-prompt")) return false;
      return ticketToTaskGenerator.hasCodingPromptContent(
        issue.fields?.description ? extractJiraBodyText(issue.fields.description) : "",
      );
    })
    .slice(0, limit)
    .map((issue: any) => ({
      id: issue.key,
      type: "jira_issue" as const,
      title: issue.fields?.summary || "",
      number: parseInt(issue.key.split("-").pop() || "0", 10),
      url: `${env.JIRA_BASE_URL}/browse/${issue.key}`,
      owner: issue.fields?.project?.key || "",
      repo: issue.fields?.project?.key || "",
      labels: issue.fields?.labels || [],
      suggestedBranch: makeBranchName(
        parseInt(issue.key.split("-").pop() || "0", 10),
        issue.fields?.summary || "",
      ),
    }));
}

async function fetchJitbitWork(
  label: string,
  limit: number,
): Promise<NormalizedWorkItem[]> {
  if (!env.JITBIT_ENABLED) {
    throw new Error("JITBIT_ENABLED must be true for Jitbit source");
  }

  const tickets = await jitbitClient.listTickets({ tagName: label });

  return tickets
    .slice(0, limit)
    .filter((ticket: any) => {
      const body = ticket.body || "";
      if (body.includes("missing-coding-prompt")) return false;
      return ticketToTaskGenerator.hasCodingPromptContent(body);
    })
    .map((ticket: any) => ({
      id: String(ticket.ticketID),
      type: "jitbit_ticket" as const,
      title: ticket.subject || "",
      number: ticket.ticketID,
      url: `${env.JITBIT_BASE_URL}/ticket/${ticket.ticketID}`,
      owner: "",
      repo: "",
      labels: ticket.tags ? ticket.tags.split(",").map((t: string) => t.trim()) : [],
      suggestedBranch: makeBranchName(ticket.ticketID, ticket.subject || ""),
    }));
}

function extractJiraBodyText(description: any): string {
  if (typeof description === "string") return description;
  // ADF format — reconstruct markdown from node types
  if (description?.content) {
    return description.content
      .map((node: any) => {
        const text = node?.content?.map((c: any) => c?.text || "").join(" ") || "";
        if (node?.type === "heading" && node?.attrs?.level) {
          return `${"#".repeat(node.attrs.level)} ${text}`;
        }
        return text;
      })
      .join("\n");
  }
  return "";
}
