import { FastifyInstance } from "fastify";
import { githubClient } from "../integrations/github/github-client";
import { ticketToTaskGenerator } from "../engineering/ticket-to-task";
import { env } from "../config/env";

const AI_BRANCH_PREFIX = "ai/issue-";
const DEFAULT_WORK_LABEL = "ready-for-agent";

export async function autonomousLoopRoutes(fastify: FastifyInstance) {
  fastify.get("/work", async (request, _reply) => {
    const query = request.query as {
      repo?: string;
      owner?: string;
      label?: string;
      limit?: string;
    };

    const owner = query.owner || env.GITHUB_DEFAULT_OWNER;
    const repo = query.repo || env.GITHUB_DEFAULT_REPO;
    const label = query.label || DEFAULT_WORK_LABEL;
    const limit = Math.min(parseInt(query.limit || "10", 10), 50);

    if (!owner || !repo) {
      return {
        success: false,
        error: "owner and repo are required (or set GITHUB_DEFAULT_OWNER/REPO)",
      };
    }

    try {
      const issues = await githubClient.listIssues("open", label, owner, repo);

      const qualifying = issues
        .filter((issue: any) => {
          if (issue.pull_request) return false;
          const issueLabels: string[] = (issue.labels || []).map((l: any) =>
            typeof l === "string" ? l : l.name,
          );
          if (issueLabels.includes("missing-coding-prompt")) return false;
          return ticketToTaskGenerator.hasCodingPromptContent(issue.body || "");
        })
        .slice(0, limit);

      return {
        success: true,
        items: qualifying.map((issue: any) => ({
          id: String(issue.number),
          type: "github_issue",
          title: issue.title,
          number: issue.number,
          url: issue.html_url,
          owner,
          repo,
          labels: (issue.labels || []).map((l: any) =>
            typeof l === "string" ? l : l.name,
          ),
          suggestedBranch: makeBranchName(issue.number, issue.title),
        })),
        total: qualifying.length,
      };
    } catch (err) {
      return { success: false, error: (err as Error).message };
    }
  });

  fastify.post("/pr", async (request, _reply) => {
    const body = request.body as {
      owner?: string;
      repo?: string;
      title: string;
      head: string;
      base?: string;
      body?: string;
      issueNumber?: number;
    };

    if (!body.title || !body.head) {
      return { success: false, error: "title and head (branch) are required" };
    }

    const owner = body.owner || env.GITHUB_DEFAULT_OWNER;
    const repo = body.repo || env.GITHUB_DEFAULT_REPO;

    if (!owner || !repo) {
      return {
        success: false,
        error: "owner and repo are required (or set GITHUB_DEFAULT_OWNER/REPO)",
      };
    }

    const prBody =
      body.body ??
      (body.issueNumber
        ? `Closes #${body.issueNumber}\n\n_Generated by AiRemoteCoder autonomous agent._`
        : "_Generated by AiRemoteCoder autonomous agent._");

    try {
      const pr = await githubClient.createPullRequest(
        {
          title: body.title,
          body: prBody,
          head: body.head,
          base: body.base || "main",
        },
        owner,
        repo,
      );

      return { success: true, prNumber: pr.number, url: pr.html_url };
    } catch (err) {
      return { success: false, error: (err as Error).message };
    }
  });

  fastify.post("/complete", async (request, _reply) => {
    const body = request.body as {
      owner?: string;
      repo?: string;
      issueNumber: number;
      prNumber: number;
      branchName: string;
      agentExitCode?: number;
    };

    if (!body.issueNumber || !body.prNumber) {
      return {
        success: false,
        error: "issueNumber and prNumber are required",
      };
    }

    const owner = body.owner || env.GITHUB_DEFAULT_OWNER;
    const repo = body.repo || env.GITHUB_DEFAULT_REPO;

    try {
      await githubClient.addIssueComment(
        body.issueNumber,
        `🤖 **AiRemoteCoder completed work**\n\n- Branch: \`${body.branchName}\`\n- PR: #${body.prNumber}\n- Exit code: ${body.agentExitCode ?? "unknown"}\n\nReview is in progress.`,
        owner,
        repo,
      );

      return { success: true, acknowledged: true };
    } catch (err) {
      return { success: false, error: (err as Error).message };
    }
  });
}

function makeBranchName(issueNumber: number, title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40);
  return slug
    ? `${AI_BRANCH_PREFIX}${issueNumber}-${slug}`
    : `${AI_BRANCH_PREFIX}${issueNumber}`;
}
