import { FastifyInstance } from "fastify";
import { githubClient } from "../integrations/github/github-client";
import { gitlabClient } from "../integrations/gitlab/gitlab-client";
import { jiraClient } from "../integrations/jira/jira-client";
import { jitbitClient } from "../integrations/jitbit/jitbit-client";
import { ticketToTaskGenerator } from "../engineering/ticket-to-task";
import { workItemDatabase } from "../work-items/database";
import { hashUuidToNumber, parseWorkItemTagsJson } from "../autonomous-loop/work-item-utils";
import { env } from "../config/env";
import type { TicketSourceType } from "../integrations/source-resolver";

const AI_BRANCH_PREFIX = "ai/issue-";
const DEFAULT_WORK_LABEL = "ready-for-agent";
const JIRA_DEPENDENCY_RE = /\b(?:depends\s+on|blocked\s+by|requires|prerequisite\s*:\s*)\s*:?\s*([A-Z][A-Z0-9]+-\d+(?:\s*,\s*[A-Z][A-Z0-9]+-\d+)*)/gi;
const DO_NOT_START_UNTIL_RE = /\bdo\s+not\s+start\b[\s\S]{0,160}?\buntil\b[\s\S]{0,80}?([A-Z][A-Z0-9]+-\d+)/gi;
const JIRA_KEY_RE = /\b[A-Z][A-Z0-9]+-\d+\b/g;

interface NormalizedWorkItem {
  id: string;
  type: string;
  title: string;
  number: number;
  url: string;
  owner: string;
  repo: string;
  labels: string[];
  suggestedBranch: string;
  body?: string;
}

export async function autonomousLoopRoutes(fastify: FastifyInstance) {
  fastify.get("/work", async (request, _reply) => {
    const query = request.query as {
      repo?: string;
      owner?: string;
      label?: string;
      limit?: string;
      source?: string;
      sprint?: string;
      skipPromptCheck?: string;
    };

    const source = (query.source || "auto") as TicketSourceType | "auto";
    const label = query.label || DEFAULT_WORK_LABEL;
    const limit = Math.min(parseInt(query.limit || "10", 10), 50);
    const skipPromptCheck = query.skipPromptCheck === "true";

    try {
      let items: NormalizedWorkItem[] = [];

      const resolvedSource = await resolveSource(source, query);

      switch (resolvedSource) {
        case "github":
          items = await fetchGitHubWork(label, limit, query, skipPromptCheck);
          break;
        case "gitlab":
          items = await fetchGitLabWork(label, limit, skipPromptCheck);
          break;
        case "jira":
          items = await fetchJiraWork(label, limit, query.repo, skipPromptCheck, query.sprint);
          break;
        case "jitbit":
          items = await fetchJitbitWork(label, limit, skipPromptCheck);
          break;
        case "work_items":
          items = await fetchWorkItemsWork(label, limit, skipPromptCheck);
          break;
      }

      return { success: true, items, total: items.length };
    } catch (err) {
      return { success: false, error: (err as Error).message };
    }
  });

  fastify.post("/pr", async (request, _reply) => {
    const body = request.body as {
      owner?: string;
      repo?: string;
      title: string;
      head: string;
      base?: string;
      body?: string;
      issueNumber?: number;
    };

    if (!body.title || !body.head) {
      return { success: false, error: "title and head (branch) are required" };
    }

    const owner = body.owner || env.GITHUB_DEFAULT_OWNER;
    const repo = body.repo || env.GITHUB_DEFAULT_REPO;

    if (!owner || !repo) {
      return {
        success: false,
        error: "owner and repo are required (or set GITHUB_DEFAULT_OWNER/REPO)",
      };
    }

    const prBody =
      body.body ??
      (body.issueNumber
        ? `Closes #${body.issueNumber}\n\n_Generated by AiRemoteCoder autonomous agent._`
        : "_Generated by AiRemoteCoder autonomous agent._");

    try {
      const pr = await githubClient.createPullRequest(
        {
          title: body.title,
          body: prBody,
          head: body.head,
          base: body.base || "main",
        },
        owner,
        repo,
      );

      return { success: true, prNumber: pr.number, url: pr.html_url };
    } catch (err: any) {
      // Surface GitHub API error details for 422 and other client errors
      const ghErrors = err?.response?.data?.errors;
      const ghMessage = err?.response?.data?.message;
      let detail = err?.message || "unknown error";
      if (ghErrors?.length) {
        detail = ghErrors.map((e: any) => e.message || JSON.stringify(e)).join("; ");
      } else if (ghMessage) {
        detail = ghMessage;
      }
      return { success: false, error: detail };
    }
  });

  fastify.post("/complete", async (request, _reply) => {
    const body = request.body as {
      owner?: string;
      repo?: string;
      issueNumber: number;
      prNumber: number;
      branchName: string;
      agentExitCode?: number;
    };

    if (!body.issueNumber || !body.prNumber) {
      return {
        success: false,
        error: "issueNumber and prNumber are required",
      };
    }

    const owner = body.owner || env.GITHUB_DEFAULT_OWNER;
    const repo = body.repo || env.GITHUB_DEFAULT_REPO;

    try {
      await githubClient.addIssueComment(
        body.issueNumber,
        `🤖 **AiRemoteCoder completed work**\n\n- Branch: \`${body.branchName}\`\n- PR: #${body.prNumber}\n- Exit code: ${body.agentExitCode ?? "unknown"}\n\nReview is in progress.`,
        owner,
        repo,
      );

      return { success: true, acknowledged: true };
    } catch (err) {
      return { success: false, error: (err as Error).message };
    }
  });

  // Create a GitLab merge request
  fastify.post("/mr", async (request, _reply) => {
    const body = request.body as {
      project?: string;
      title: string;
      sourceBranch: string;
      targetBranch?: string;
      description?: string;
      labels?: string;
      removeSourceBranch?: boolean;
    };

    if (!body.title || !body.sourceBranch) {
      return { success: false, error: "title and sourceBranch are required" };
    }

    const projectId = body.project || env.GITLAB_DEFAULT_PROJECT;
    if (!projectId) {
      return { success: false, error: "project is required (or set GITLAB_DEFAULT_PROJECT)" };
    }

    try {
      const mr = await gitlabClient.createMergeRequest(projectId, {
        title: body.title,
        sourceBranch: body.sourceBranch,
        targetBranch: body.targetBranch || "main",
        description: body.description ?? "_Generated by AiRemoteCoder autonomous agent._",
        labels: body.labels,
        removeSourceBranch: body.removeSourceBranch ?? true,
      });

      return {
        success: true,
        mrIid: mr.iid,
        url: mr.web_url,
      };
    } catch (err) {
      return { success: false, error: (err as Error).message };
    }
  });

  // Post completion comment on a Jira issue
  fastify.post("/complete/jira", async (request, _reply) => {
    const body = request.body as {
      issueKey: string;
      branchName: string;
      mrUrl?: string;
      mrIid?: number;
      agentExitCode?: number;
    };

    if (!body.issueKey) {
      return { success: false, error: "issueKey is required" };
    }

    try {
      const commentBody = `🤖 **AiRemoteCoder completed work**\n\n- Branch: \`${body.branchName}\`${body.mrUrl ? `\n- MR: ${body.mrUrl}` : body.mrIid ? `\n- MR: !${body.mrIid}` : ""}\n- Exit code: ${body.agentExitCode ?? "unknown"}\n\nReview is in progress.`;

      await jiraClient.addComment(body.issueKey, commentBody);

      return { success: true, acknowledged: true };
    } catch (err) {
      return { success: false, error: (err as Error).message };
    }
  });
}

export function makeBranchName(issueNumber: number, title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40);
  return slug
    ? `${AI_BRANCH_PREFIX}${issueNumber}-${slug}`
    : `${AI_BRANCH_PREFIX}${issueNumber}`;
}

function resolveSource(
  source: TicketSourceType | "auto",
  query: { owner?: string; repo?: string },
): TicketSourceType {
  if (source !== "auto") return source;

  // Auto-detect: use whichever integration is configured
  if (query.owner || query.repo || env.GITHUB_DEFAULT_OWNER || env.GITHUB_DEFAULT_REPO) {
    return "github";
  }
  if (env.GITLAB_DEFAULT_PROJECT) return "gitlab";
  if (env.JIRA_BASE_URL) return "jira";
  if (env.JITBIT_ENABLED) return "jitbit";

  return "github";
}

async function fetchGitHubWork(
  label: string,
  limit: number,
  query: { owner?: string; repo?: string },
  skipPromptCheck: boolean = false,
): Promise<NormalizedWorkItem[]> {
  const owner = query.owner || env.GITHUB_DEFAULT_OWNER;
  const repo = query.repo || env.GITHUB_DEFAULT_REPO;

  if (!owner || !repo) {
    throw new Error("owner and repo are required for GitHub (or set GITHUB_DEFAULT_OWNER/REPO)");
  }

  const issues = await githubClient.listIssues("open", label, owner, repo);

  const filtered: any[] = [];
  for (const issue of issues) {
    if (issue.pull_request) continue;
    const issueLabels: string[] = (issue.labels || []).map((l: any) =>
      typeof l === "string" ? l : l.name,
    );
    if (skipPromptCheck) { filtered.push(issue); continue; }
    if (ticketToTaskGenerator.hasCodingPromptContent(issue.body || "")) {
      filtered.push(issue);
      continue;
    }
    // Description didn't match — check comments for coding prompt content
    try {
      const comments = await githubClient.listIssueComments(issue.number, owner, repo);
      const hasPromptInComments = comments.some((c: any) =>
        ticketToTaskGenerator.hasCodingPromptContent(c.body || ""),
      );
      if (hasPromptInComments) {
        console.log(`[GitHub] Issue #${issue.number}: coding prompt found in comments (not body)`);
        filtered.push(issue);
      } else if (issueLabels.includes("missing-coding-prompt")) {
        console.log(`[GitHub] Skipping issue #${issue.number}: has "missing-coding-prompt" label and no coding prompt in body/comments`);
      }
    } catch {
      // Comments unavailable — skip issue
    }
  }

  return filtered
    .slice(0, limit)
    .map((issue: any) => ({
      id: String(issue.number),
      type: "github_issue" as const,
      title: issue.title,
      number: issue.number,
      url: issue.html_url,
      owner,
      repo,
      labels: (issue.labels || []).map((l: any) =>
        typeof l === "string" ? l : l.name,
      ),
      suggestedBranch: makeBranchName(issue.number, issue.title),
      body: issue.body || "",
    }));
}

async function fetchGitLabWork(
  label: string,
  limit: number,
  skipPromptCheck: boolean = false,
): Promise<NormalizedWorkItem[]> {
  if (!env.GITLAB_DEFAULT_PROJECT) {
    throw new Error("GITLAB_DEFAULT_PROJECT is required for GitLab source");
  }

  const issues = await gitlabClient.listIssues(
    env.GITLAB_DEFAULT_PROJECT,
    "opened",
    label,
  );

  const filtered: any[] = [];
  for (const issue of issues) {
    const issueLabels: string[] = (issue.labels || []);
    if (skipPromptCheck) { filtered.push(issue); continue; }
    if (ticketToTaskGenerator.hasCodingPromptContent(issue.description || "")) {
      filtered.push(issue);
      continue;
    }
    // Description didn't match — check issue notes for coding prompt content
    try {
      const notes = await gitlabClient.listIssueNotes(env.GITLAB_DEFAULT_PROJECT, issue.iid);
      const hasPromptInNotes = notes.some((n: any) =>
        ticketToTaskGenerator.hasCodingPromptContent(n.body || ""),
      );
      if (hasPromptInNotes) {
        console.log(`[GitLab] Issue !${issue.iid}: coding prompt found in notes (not description)`);
        filtered.push(issue);
      } else if (issueLabels.includes("missing-coding-prompt")) {
        console.log(`[GitLab] Skipping issue !${issue.iid}: has "missing-coding-prompt" label and no coding prompt in description/notes`);
      }
    } catch {
      // Notes unavailable — skip issue
    }
  }

  return filtered
    .slice(0, limit)
    .map((issue: any) => ({
      id: String(issue.iid),
      type: "gitlab_issue" as const,
      title: issue.title,
      number: issue.iid,
      url: issue.web_url,
      owner: String(issue.project_id),
      repo: env.GITLAB_DEFAULT_PROJECT!,
      labels: issue.labels || [],
      suggestedBranch: makeBranchName(issue.iid, issue.title),
      body: issue.description || "",
    }));
}

async function fetchJiraWork(
  label: string,
  limit: number,
  repoFilter?: string,
  skipPromptCheck: boolean = false,
  sprintFocus?: string,
): Promise<NormalizedWorkItem[]> {
  if (!env.JIRA_BASE_URL) {
    throw new Error("JIRA_BASE_URL is required for Jira source");
  }

  // Build JQL query with optional repo label filter.
  // The repo name (e.g. "hawk-soar-cloud-v3") is stored as a Jira label on the ticket.
  // Strip any prefix like "gitlab:" from the repo filter.
  // Use statusCategory keys (new/indeterminate) not display names — Jira JQL
  // accepts category keys, not the user-visible "To Do"/"In Progress" labels.
  let jql: string;
  if (repoFilter) {
    const repoLabel = repoFilter.replace(/^(gitlab:|github:)/i, "");
    jql = `labels = "${label}" AND labels = "${repoLabel}" AND statusCategory in (new, indeterminate) ORDER BY priority ASC`;
  } else {
    jql = `labels = "${label}" AND statusCategory in (new, indeterminate) ORDER BY priority ASC`;
  }
  const candidateLimit = Math.min(Math.max(limit * 5, 25), 100);
  const issues = await jiraClient.searchIssues(jql, candidateLimit);

  console.log(`[Jira] fetchJiraWork: JQL="${jql}" returned ${issues.length} issues`);

  const explicitSprint = normalizeSprintFocus(sprintFocus);
  const autoSprint = explicitSprint === null ? getEarliestSprintNumber(issues) : null;
  if (explicitSprint) {
    console.log(`[Jira] Sprint focus: ${explicitSprint.label}`);
  } else if (autoSprint !== null) {
    console.log(`[Jira] Auto sprint focus: sprint-${autoSprint}`);
  }

  const filtered: any[] = [];
  for (const issue of issues) {
    if (explicitSprint) {
      const issueSprint = extractJiraSprintNumber(issue);
      if (!matchesSprintFocus(issue, explicitSprint)) {
        console.log(`[Jira] Skipping ${issue.key}: outside sprint focus ${explicitSprint.label}${issueSprint === null ? "" : ` (issue sprint-${issueSprint})`}`);
        continue;
      }
    } else if (autoSprint !== null) {
      const issueSprint = extractJiraSprintNumber(issue);
      if (issueSprint !== autoSprint) {
        console.log(`[Jira] Skipping ${issue.key}: outside auto sprint focus sprint-${autoSprint}${issueSprint === null ? "" : ` (issue sprint-${issueSprint})`}`);
        continue;
      }
    }

    const issueLabels: string[] = issue.fields?.labels || [];
    if (skipPromptCheck) {
      filtered.push(issue);
      continue;
    }
    const body = issue.fields?.description ? extractJiraBodyText(issue.fields.description) : "";
    let comments: Array<{ body: string }> = [];
    try {
      comments = await jiraClient.getComments(issue.key);
    } catch (err) {
      console.log(`[Jira] ${issue.key}: could not fetch comments (${(err as Error).message})`);
    }
    const dependencyText = [body, ...comments.map((c) => c.body || "")].filter(Boolean).join("\n");
    const unresolvedDeps = await getUnresolvedJiraDependencyRefs(issue.key, dependencyText);
    if (unresolvedDeps.length > 0) {
      console.log(`[Jira] Skipping ${issue.key}: blocked by unresolved dependencies ${unresolvedDeps.join(", ")}`);
      continue;
    }

    if (ticketToTaskGenerator.hasCodingPromptContent(body)) {
      filtered.push(issue);
      continue;
    }
    const hasPromptInComments = comments.some((c: any) =>
      ticketToTaskGenerator.hasCodingPromptContent(c.body || ""),
    );
    if (hasPromptInComments) {
      console.log(`[Jira] ${issue.key}: coding prompt found in comments (not description)`);
      filtered.push(issue);
    } else if (issueLabels.includes("missing-coding-prompt")) {
      console.log(`[Jira] Skipping ${issue.key}: has "missing-coding-prompt" label and no coding prompt in description/comments`);
    } else {
      console.log(`[Jira] Skipping ${issue.key} ("${issue.fields?.summary || ""}"): no coding prompt content in description or comments (desc first 200 chars: ${body.slice(0, 200).replace(/\n/g, " ")})`);
    }
  }

  return filtered
    .slice(0, limit)
    .map((issue: any) => ({
      id: issue.key,
      type: "jira_issue" as const,
      title: issue.fields?.summary || "",
      number: parseInt(issue.key.split("-").pop() || "0", 10),
      url: `${env.JIRA_BASE_URL}/browse/${issue.key}`,
      owner: issue.fields?.project?.key || "",
      repo: issue.fields?.project?.key || "",
      labels: issue.fields?.labels || [],
      suggestedBranch: makeBranchName(
        parseInt(issue.key.split("-").pop() || "0", 10),
        issue.fields?.summary || "",
      ),
      body: issue.fields?.description ? extractJiraBodyText(issue.fields.description) : "",
    }));
}

async function fetchJitbitWork(
  label: string,
  limit: number,
  skipPromptCheck: boolean = false,
): Promise<NormalizedWorkItem[]> {
  if (!env.JITBIT_ENABLED) {
    throw new Error("JITBIT_ENABLED must be true for Jitbit source");
  }

  const tickets = await jitbitClient.listTickets({ tagName: label });

  return tickets
    .slice(0, limit)
    .filter((ticket: any) => {
      const body = ticket.body || "";
      if (body.includes("missing-coding-prompt")) return false;
      if (skipPromptCheck) return true;
      return ticketToTaskGenerator.hasCodingPromptContent(body);
    })
    .map((ticket: any) => ({
      id: String(ticket.ticketID),
      type: "jitbit_ticket" as const,
      title: ticket.subject || "",
      number: ticket.ticketID,
      url: `${env.JITBIT_BASE_URL}/ticket/${ticket.ticketID}`,
      owner: "",
      repo: "",
      labels: ticket.tags ? ticket.tags.split(",").map((t: string) => t.trim()) : [],
      suggestedBranch: makeBranchName(ticket.ticketID, ticket.subject || ""),
      body: ticket.body || "",
    }));
}

function extractJiraBodyText(description: any): string {
  if (typeof description === "string") return description;
  // ADF format — reconstruct markdown from node types
  if (description?.content) {
    return description.content
      .map((node: any) => {
        const text = node?.content?.map((c: any) => c?.text || "").join(" ") || "";
        if (node?.type === "heading" && node?.attrs?.level) {
          return `${"#".repeat(node.attrs.level)} ${text}`;
        }
        return text;
      })
      .join("\n");
  }
  return "";
}

function parseJiraDependencyRefs(text: string): string[] {
  const refs = new Set<string>();
  let match: RegExpExecArray | null;

  const dependencyRe = new RegExp(JIRA_DEPENDENCY_RE.source, JIRA_DEPENDENCY_RE.flags);
  while ((match = dependencyRe.exec(text)) !== null) {
    const keys = match[1].match(JIRA_KEY_RE) || [];
    for (const key of keys) refs.add(key.toUpperCase());
  }

  const doNotStartRe = new RegExp(DO_NOT_START_UNTIL_RE.source, DO_NOT_START_UNTIL_RE.flags);
  while ((match = doNotStartRe.exec(text)) !== null) {
    refs.add(match[1].toUpperCase());
  }

  return [...refs];
}

export function normalizeSprintFocus(value?: string): { number: number | null; label: string } | null {
  const raw = value?.trim();
  if (!raw) return null;
  const match = raw.match(/^(?:sprint[\s\-_:]*)?(\d+)$/i) || raw.match(/\bsprint[\s\-_:]*(\d+)\b/i);
  if (match) {
    const number = parseInt(match[1], 10);
    return Number.isFinite(number) ? { number, label: `sprint-${number}` } : null;
  }
  return { number: null, label: raw.toLowerCase() };
}

export function extractJiraSprintNumber(issue: any): number | null {
  const summary = String(issue.fields?.summary || "");
  const titleMatch = summary.match(/\[\s*sprint[\s\-]+(\d+)\s*\]/i);
  if (titleMatch) return parseInt(titleMatch[1], 10);

  const labels: string[] = issue.fields?.labels || [];
  for (const label of labels) {
    const labelMatch = String(label).match(/^(?:sprint[\s\-:]*|s)(\d+)$/i);
    if (labelMatch) return parseInt(labelMatch[1], 10);
  }

  return null;
}

export function matchesSprintFocus(issue: any, focus: { number: number | null; label: string }): boolean {
  if (focus.number !== null) {
    return extractJiraSprintNumber(issue) === focus.number;
  }

  const haystack = [
    issue.fields?.summary || "",
    ...(issue.fields?.labels || []),
  ].join(" ").toLowerCase();
  return haystack.includes(focus.label);
}

export function getEarliestSprintNumber(issues: any[]): number | null {
  const sprints = issues
    .map((issue) => extractJiraSprintNumber(issue))
    .filter((sprint): sprint is number => sprint !== null);
  return sprints.length === 0 ? null : Math.min(...sprints);
}

function isJiraDoneStatus(status: string | undefined): boolean {
  return /done|closed|resolved|completed/i.test(status || "");
}

async function getUnresolvedJiraDependencyRefs(issueKey: string, text: string): Promise<string[]> {
  const deps = parseJiraDependencyRefs(text).filter((dep) => dep !== issueKey);
  const unresolved: string[] = [];
  for (const dep of deps) {
    try {
      const depIssue = await jiraClient.getIssue(dep);
      const status = depIssue.fields.status?.name ?? "";
      if (!isJiraDoneStatus(status)) {
        unresolved.push(`${dep} (${status || "unknown status"})`);
      }
    } catch (err) {
      unresolved.push(`${dep} (${err instanceof Error ? err.message : "could not verify status"})`);
    }
  }
  return unresolved;
}

async function fetchWorkItemsWork(
  label: string,
  limit: number,
  skipPromptCheck: boolean = false,
): Promise<NormalizedWorkItem[]> {
  const result = workItemDatabase.listWorkItems({ limit: 200 });
  const filtered: NormalizedWorkItem[] = [];

  for (const wi of result.items) {
    // Skip done and archived items
    if (wi.archived) continue;

    const tags = parseWorkItemTagsJson(wi.tagsJson);
    // Only include items with the label tag (e.g., "ready-for-agent")
    if (!tags.some((t) => t.toLowerCase() === label.toLowerCase())) continue;

    // Coding prompt check
    if (!skipPromptCheck) {
      const body = wi.description || "";
      if (!ticketToTaskGenerator.hasCodingPromptContent(body)) continue;
    }

    const issueNum = hashUuidToNumber(wi.id);

    filtered.push({
      id: wi.id,
      type: "work_item" as const,
      title: wi.title,
      number: issueNum,
      url: "",
      owner: wi.owner || "",
      repo: "",
      labels: tags,
      suggestedBranch: makeBranchName(issueNum, wi.title),
      body: wi.description || "",
    });
  }

  return filtered.slice(0, limit);
}
