/**
 * PR / MR creation for GitHub and GitLab.
 *
 * All functions accept explicit parameters — no module-level state.
 * Returns typed results rather than calling process.exit() on failure.
 */

import { spawnSync } from "child_process";
import axios from "axios";
import { gitlabClient } from "../integrations/gitlab/gitlab-client";
import type { ServerConfig, WorkItem, PipelineLogger } from "./types";

const noop: PipelineLogger = {
  logGit: () => {},
  logError: () => {},
  logConfig: () => {},
  logWork: () => {},
  logAgent: () => {},
};

// ── Platform detection ────────────────────────────────────────────────────────

export function detectRemotePlatform(
  workspace: string,
): "github" | "gitlab" | "unknown" {
  const result = spawnSync("git", ["remote", "get-url", "origin"], {
    cwd: workspace, stdio: "pipe", encoding: "utf-8",
  });
  if (result.status !== 0 || !result.stdout.trim()) return "unknown";
  const url = result.stdout.trim().toLowerCase();
  if (url.includes("github.com")) return "github";
  if (url.includes("gitlab")) return "gitlab";
  return "unknown";
}

/**
 * Extract the GitLab project path from the git remote URL.
 * Returns the URL-encoded path suitable for GitLab API calls.
 */
export function getGitLabProjectFromRemote(workspace: string): string | null {
  const result = spawnSync("git", ["remote", "get-url", "origin"], {
    cwd: workspace, stdio: "pipe", encoding: "utf-8",
  });
  if (result.status !== 0 || !result.stdout.trim()) return null;

  const url = result.stdout.trim();
  let projectPath: string | null = null;

  const httpsMatch = url.match(/^https?:\/\/[^/]+\/(.+?)(?:\.git)?$/i);
  if (httpsMatch) projectPath = httpsMatch[1];

  const sshMatch = url.match(/^git@[^:]+:(.+?)(?:\.git)?$/i);
  if (sshMatch) projectPath = sshMatch[1];

  if (!projectPath) return null;
  return encodeURIComponent(projectPath);
}

// ── Find existing PRs / MRs ───────────────────────────────────────────────────

export async function findExistingGitLabMR(
  projectId: string,
  sourceBranch: string,
): Promise<{ iid: number; web_url: string } | null> {
  try {
    const mrs = await gitlabClient.getMergeRequests(projectId, "opened");
    const existing = (mrs || []).find((mr: any) => mr.source_branch === sourceBranch);
    return existing ? { iid: existing.iid, web_url: existing.web_url } : null;
  } catch {
    return null;
  }
}

export async function findExistingGitHubPR(
  ghToken: string | undefined,
  owner: string,
  repo: string,
  branchName: string,
): Promise<{ number: number; html_url: string } | null> {
  if (!ghToken || !owner || !repo) return null;
  try {
    const resp = await axios.get(
      `https://api.github.com/repos/${owner}/${repo}/pulls`,
      {
        params: { state: "open", head: `${owner}:${branchName}`, per_page: 5 },
        headers: { Authorization: `Bearer ${ghToken}`, Accept: "application/vnd.github+json" },
      },
    );
    const prs = resp.data;
    return prs.length > 0 ? { number: prs[0].number, html_url: prs[0].html_url } : null;
  } catch {
    return null;
  }
}

// ── PR / MR creation ──────────────────────────────────────────────────────────

export function authHeaders(cfg: ServerConfig): Record<string, string> {
  return { Authorization: `Bearer ${cfg.apiKey}` };
}

export async function createPR(
  cfg: ServerConfig,
  item: WorkItem,
  branchName: string,
  workspace: string,
  baseBranch: string,
  logger: PipelineLogger = noop,
): Promise<{ prNumber: number; url: string } | null> {
  const platform = detectRemotePlatform(workspace);
  logger.logGit(`Detected remote platform: ${platform}`);

  if (platform === "gitlab") {
    const gitlabProject =
      getGitLabProjectFromRemote(workspace) ||
      process.env.GITLAB_DEFAULT_PROJECT ||
      cfg.repo ||
      item.repo;

    const description = item.url
      ? `Closes ${item.url}\n\nIssue: ${item.id}\n\n_Generated by AiRemoteCoder autonomous agent._`
      : `Issue: ${item.id}\n\n_Generated by AiRemoteCoder autonomous agent._`;

    try {
      const resp = await axios.post<{
        success: boolean;
        mrIid?: number;
        url?: string;
        error?: string;
      }>(
        `${cfg.apiUrl}/api/autonomous-loop/mr`,
        {
          project: gitlabProject,
          title: `[AI] ${item.title}`,
          sourceBranch: branchName,
          targetBranch: baseBranch,
          description,
          removeSourceBranch: true,
        },
        { headers: authHeaders(cfg) },
      );

      if (resp.data.success) {
        return { prNumber: resp.data.mrIid ?? 0, url: resp.data.url ?? "" };
      }

      const errMsg = resp.data.error ?? "";
      if (errMsg.includes("already exists")) {
        logger.logGit(`MR already exists for branch ${branchName} — looking up existing MR`);
        const existing = await findExistingGitLabMR(gitlabProject, branchName);
        if (existing) {
          logger.logGit(`Found existing MR !${existing.iid}: ${existing.web_url}`);
          return { prNumber: existing.iid, url: existing.web_url };
        }
      }

      logger.logError(`GitLab MR creation failed: ${errMsg}`);
      return null;
    } catch (err) {
      const errMsg = (err as Error).message;
      if (errMsg.includes("already exists")) {
        const existing = await findExistingGitLabMR(gitlabProject, branchName);
        if (existing) {
          logger.logGit(`Found existing MR !${existing.iid}: ${existing.web_url}`);
          return { prNumber: existing.iid, url: existing.web_url };
        }
      }
      logger.logError(`GitLab MR creation failed: ${errMsg}`);
      return null;
    }
  }

  // Default: GitHub PR
  const ghToken = process.env.GITHUB_TOKEN;
  const owner = item.owner || cfg.owner || "redsand";
  const repo = item.repo || cfg.repo || "";

  try {
    const resp = await axios.post<{ success: boolean; prNumber: number; url: string }>(
      `${cfg.apiUrl}/api/autonomous-loop/pr`,
      {
        owner,
        repo,
        title: `[AI] ${item.title}`,
        head: branchName,
        base: baseBranch,
        issueNumber: item.number,
      },
      { headers: authHeaders(cfg) },
    );

    if (resp.data.success) {
      return { prNumber: resp.data.prNumber, url: resp.data.url };
    }

    const errMsg =
      (resp.data as any).error ?? (resp.data as any).message ?? "";
    if (
      errMsg.includes("already exists") ||
      errMsg.includes("already open") ||
      errMsg.includes("422") ||
      errMsg.includes("Validation Failed")
    ) {
      logger.logGit(`PR already exists for branch ${branchName} — looking up existing PR`);
      const existing = await findExistingGitHubPR(ghToken, owner, repo, branchName);
      if (existing) {
        logger.logGit(`Found existing PR #${existing.number}: ${existing.html_url}`);
        return { prNumber: existing.number, url: existing.html_url };
      }
    }

    logger.logError(`GitHub PR creation failed: ${errMsg || "unknown error"}`);
    return null;
  } catch (err: any) {
    const errMsg = (err as Error).message;
    const status = err?.response?.status;
    if (
      status === 422 ||
      errMsg.includes("already exists") ||
      errMsg.includes("already open") ||
      errMsg.includes("Validation Failed")
    ) {
      const existing = await findExistingGitHubPR(ghToken, owner, repo, branchName);
      if (existing) {
        logger.logGit(`Found existing PR #${existing.number}: ${existing.html_url}`);
        return { prNumber: existing.number, url: existing.html_url };
      }
    }
    logger.logError(`PR creation failed: ${errMsg}`);
    return null;
  }
}

// ── Utilities ─────────────────────────────────────────────────────────────────

export function truncate(text: string, maxLen: number): string {
  if (text.length <= maxLen) return text;
  return text.slice(0, maxLen - 1) + "…";
}

export function extractIssueKeyFromBranchName(branchName: string): string | null {
  const match = branchName.match(/(?:issue[-/])([A-Z]+-\d+|\d+)/i);
  return match ? match[1] : null;
}
